apiVersion: apps/v1
kind: Deployment
metadata:
  name: airline-satisfaction
  labels:
    app: airline-satisfaction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airline-satisfaction
  template:
    metadata:
      labels:
        app: airline-satisfaction
    spec:
      containers:
        - name: airline-satisfaction
          image: checkamani/airline-satisfaction:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
