apiVersion: v1
kind: Service
metadata:
  name: airline-satisfaction-svc
  labels:
    app: airline-satisfaction
spec:
  type: NodePort
  selector:
    app: airline-satisfaction
  ports:
    - name: http
      port: 80
      targetPort: 8080
